version: "3.8"
services:
  bot:
    container_name: bot
    build: .
    volumes:
      - ./.latexmkrc:/workdir/.latexmkrc
      - ./texmf.cnf:/usr/local/texlive/2022/texmf.cnf
      - ./target/TwitterLaTeXBot-1.0-SNAPSHOT-jar-with-dependencies.jar:/workdir/bot.jar
      - ./tex:/workdir
      - ./settings.properties:/workdir/settings.properties
      - ./twitter4j.properties:/workdir/twitter4j.properties
      - ./tweets.db:/workdir/tweets.db
    ports:
      - "8080:8080"
    command: sh -c "java -jar -Dfile.encoding=UTF-8 bot.jar"

